spring.application.name=ProjectsManagement_BE

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=abc;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=12345
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop

app.jwtSecret=G8xgqcqGygeWjZw+K2pGMeod35sXnHaBvKXjE4mgGzU=
app.jwtExpirationSeconds=3600

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

